print ("hi user, i am your computer. i dont know much about you.")
name = input ("what is your name?")
print ("hello " + name + " you are looking lovely today!")
age = input ("how old are you?")
age = int(11)
your_age = input ("you are " + str( int(age) * 365) + " days old")
print (" hello there " + name)
print (" you are " + name + " and you are " + age + " years old")
frend = input ("who is your best frends name?")

